apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-apps-no-grpc-provider-no-grpc
  namespace: registry-engine
  labels:
    kyverno.io/registry-provider: "true"
data:
  enabled: "false"
  namespace: apps-no-grpc
  deployment: provider-no-grpc
  generation: "1"
  reason: "No port with appProtocol: grpc found in Service"
