repositories:
  - name: gitea-charts
    url: https://dl.gitea.com/charts/

releases:
  - name: gitea
    namespace: gitea
    createNamespace: true
    chart: gitea-charts/gitea
    version: "12.5.0"
    values:
      - values/gitea.yaml
    wait: true
    waitForJobs: true
